[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"

[jp]
  languageName = "日本語"
  contentDir = "content/jp"
  weight = 15
  [jp.params]
    languageISO = "JP"
    titleHome = "ホーム"
    footer = "このサイトは<a href=\"https://gohugo.io/\">Hugo</a>と<a href=\"https://getdoks.org/\">Doks</a>を使用しています。"
    description = "クロマティックの音楽の可視化は確かに音楽に反応する実時間グラフィックを作成します。"