[[docs]]
  name = "General"
  weight = 10
  identifier = "general"
  url = "/docs/general/"

[[docs]]
  name = "Sources"
  weight = 50
  identifier = "sources"
  url = "/docs/sources/"

[[docs]]
  name = "NoteFinder"
  weight = 60
  identifier = "notefinder"
  url = "/docs/notefinder/"

[[docs]]
  name = "Visualizers"
  weight = 70
  identifier = "visualizers"
  url = "/docs/visualizers/"

[[docs]]
  name = "Outputs"
  weight = 80
  identifier = "outputs"
  url = "/docs/outputs/"

[[docs]]
  name = "Controllers"
  weight = 90
  identifier = "controllers"
  url = "/docs/controllers/"

[[main]]
  name = "Docs"
  url = "/docs/general/gettingstarted/"
  weight = 10

[[main]]
  name = "GitHub"
  url = "https://github.com/CaiB/ColorChord.NET"
  weight = 20

[[main]]
  name = "Background"
  url = "/blog/"
  weight = 30
